//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OlympicGamesEntities : DbContext
    {
        public OlympicGamesEntities()
            : base("name=OlympicGamesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<KindsOfSport> KindsOfSport { get; set; }
        public virtual DbSet<Olympiads> Olympiads { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<Results> Results { get; set; }
    }
}
